---
- name: Get GitHub runner token using API
  ansible.builtin.uri:
    url: "https://api.github.com/repos/{{ github_owner }}/{{ github_repo }}/actions/runners/registration-token"
    method: POST
    headers:
      Accept: "application/vnd.github+json"
      Authorization: "Bearer {{ github_personal_access_token }}"
      X-GitHub-Api-Version: "2022-11-28"
    status_code: [200, 201]
  register: token_response

- name: Check if token was retrieved successfully
  assert:
    that:
      - token_response.status in [200, 201]
    fail_msg: "Failed to retrieve GitHub runner token"

- name: Save token to variable
  set_fact:
    runner_token: "{{ token_response.json.token }}"

- name: Get hostname
  command: hostname
  register: hostname_result

- name: Write environment variables to .env file
  ansible.builtin.copy:
    dest: "{{ ansible_user_dir }}/docker-compose/.env"
    content: |
      GIT_REPO={{ github_owner }}/{{ github_repo }}
      RUNNER_TOKEN={{ runner_token }}
      RUNNER_NAME={{ hostname_result.stdout }}-runner  # Добавлено имя хоста для раннера

- name: Run Docker Compose
  shell: docker compose up -d
  args:
    chdir: "{{ ansible_user_dir }}/docker-compose"
