---
- name: Ensure user github_runner exists
  user:
    name: github_runner
    comment: "GitHub Actions Runner User"
    shell: /bin/bash
    createhome: yes

- name: Install ACL package
  package:
    name: acl
    state: present
