---
- name: Ensure user github_runner exists
  user:
    name: github_runner
    comment: "GitHub Actions Runner User"
    shell: /bin/bash
    createhome: yes

- name: Add user github_runner to the sudo group
  user:
    name: github_runner
    groups: sudo
    append: yes

- name: Ensure the user has root privileges (optional)
  lineinfile:
    path: /etc/sudoers
    regexp: "^github_runner"
    line: "github_runner ALL=(ALL:ALL) ALL"
    validate: '/usr/sbin/visudo -cf %s'

- name: Install ACL package
  package:
    name: acl
    state: present
