name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Ensure Docker is accessible
        run: |
          # Создаём пользователя deployer, если его нет
          if ! id "deployer" &>/dev/null; then
            sudo useradd -m deployer
            sudo usermod -aG docker deployer
          fi

          # Переключаемся на пользователя deployer и обновляем группы
          echo "Switching to user deployer"
          sudo -i -u deployer bash -c "newgrp docker && docker version"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          cd MVC-DevOps/CI-CD/API
          docker build -t scelle/mvc-api .

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            if [ $(docker ps -q -f name=mvc-api) ]; then
              docker stop mvc-api && docker rm mvc-api
            fi
            docker save scelle/mvc-api | ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} docker load
            docker run -d --name mvc-api --network server-net -p 8080:8080 scelle/mvc-api
            for i in {1..10}; do
              if curl -s http://localhost/health | grep "OK" > /dev/null; then
                echo "Container is healthy!"
                exit 0
              fi
              echo "Waiting for container to become healthy... ($i/10)"
              sleep 5
            done
            echo "Container failed to start or is unhealthy."
            exit 1
