name: Deploy API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Change docker socket owner
        run: |
          sudo chown :docker /var/run/docker.sock

      - name: Switch to runner user
        run: |
          sudo -i -u runner bash -c "whoami"

      - name: Build Docker image
        run: |
          cd MVC-DevOps/CI-CD/API
          docker build -t scelle/mvc-api .

      - name: Stop and remove old container
        run: |
          if docker ps -a --format '{{.Names}}' | grep -q '^mvc-api$'; then
            docker stop mvc-api && docker rm mvc-api
          fi

      - name: Run new container
        run: |
          docker run -d --name mvc-api -p 8080:8080 scelle/mvc-api

      - name: Check api work
        run: |
          curl http://45.144.235.149:8080/get/Clients